import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {

  NavigationMenuItem,
  NavigationMenuLink,

  navigationMenuTriggerStyle,
} from "@/components/ui/navigation-menu"
import { Link, NavigationMenu, NavigationMenuList } from "@radix-ui/react-navigation-menu";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} px-6 pt-6`}  >
        <div className="w-full flex items-center">
          <h1 className="scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl">
            Nick Hermann
          </h1>
        </div>
        {children}
      </body>
    </html >
  );
}
